baseURL = "https://VerdantAI.github.io"
languageCode = "en-us"
title = "Verdant AI"
theme = "ananke"
canonifyURLs = true

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  featured_image= '/images/ls.jpg'
  AuthorName = "Brian Dolan"
  github = "https://github.com/VerdantAI"
  linkedin = "https://www.linkedin.com/in/buddha314/"
  SidebarRecentLimit = 5
  Subtitle = "An Abundance of Living Ideas"
